In [54]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.7/dist-packages (0.1.70)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.27.1)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.10)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.5)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.8.0)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)

In [58]:
import pandas as pd
import yfinance as yf
import datetime as dt
import time
import requests
import io

In [59]:
start = dt.datetime(2014,1,1)
end = dt.datetime(2022,3,1)

In [60]:
sgx = pd.read_csv("SGXData_mainboard_active.csv")

In [62]:
# Getting the Trading Code only and turn it into a list of string
Symbols = sgx['Trading Code'].tolist()

def add_SI(x):
  new_lst = []
  for ele in x:
    ele = ele + '.SI'
    new_lst.append(ele)
  return new_lst

Symbols = add_SI(Symbols)
Symbols.insert(0, "^STI")
Symbols

['^STI',
 '1B0.SI',
 '1F2.SI',
 '1F3.SI',
 '1R6.SI',
 '49B.SI',
 '500.SI',
 '528.SI',
 '533.SI',
 '543.SI',
 '544.SI',
 '554.SI',
 '558.SI',
 '564.SI',
 '566.SI',
 '569.SI',
 '570.SI',
 '573.SI',
 '575.SI',
 '579.SI',
 '596.SI',
 '5AB.SI',
 '5AU.SI',
 '5CF.SI',
 '5CP.SI',
 '5DD.SI',
 '5DM.SI',
 '5DO.SI',
 '5DP.SI',
 '5GD.SI',
 '5GI.SI',
 '5GJ.SI',
 '5IC.SI',
 '5IG.SI',
 '5JK.SI',
 '5JS.SI',
 '5KI.SI',
 '5LY.SI',
 '5MZ.SI',
 '5NF.SI',
 '5NV.SI',
 '5PC.SI',
 '5SO.SI',
 '5SR.SI',
 '5TT.SI',
 '5UX.SI',
 '5VJ.SI',
 '5VS.SI',
 '8A1.SI',
 '8AZ.SI',
 '8U7U.SI',
 '9CI.SI',
 'A04.SI',
 'A17U.SI',
 'A26.SI',
 'A30.SI',
 'A31.SI',
 'A33.SI',
 'A34.SI',
 'A50.SI',
 'A55.SI',
 'A7RU.SI',
 'ACV.SI',
 'ADN.SI',
 'AGS.SI',
 'AIY.SI',
 'AJ2.SI',
 'AJBU.SI',
 'AP4.SI',
 'AU8U.SI',
 'AUE.SI',
 'AVM.SI',
 'AVX.SI',
 'AW9U.SI',
 'AWC.SI',
 'AWE.SI',
 'AWG.SI',
 'AWI.SI',
 'AWK.SI',
 'AWM.SI',
 'AWS.SI',
 'AWV.SI',
 'AWX.SI',
 'AWZ.SI',
 'AXB.SI',
 'AYN.SI',
 'AYV.SI',
 'AZA.SI',
 'AZT.SI',
 'B26.SI',
 'B28.SI',
 'B49.SI',
 'B58.SI',
 'B61.SI',
 'B69.SI',
 'B73.SI',
 'B9S.SI',
 'BAZ.SI',
 'BBP.SI',
 'BBW.SI',
 'BCD.SI',
 'BCV.SI',
 'BCY.SI',
 'BCZ.SI',
 'BDA.SI',
 'BDF.SI',
 'BDR.SI',
 'BDU.SI',
 'BDX.SI',
 'BEC.SI',
 'BEH.SI',
 'BEI.SI',
 'BEW.SI',
 'BEZ.SI',
 'BFI.SI',
 'BFK.SI',
 'BFT.SI',
 'BFU.SI',
 'BHD.SI',
 'BHK.SI',
 'BHU.SI',
 'BIP.SI',
 'BIX.SI',
 'BJD.SI',
 'BJW.SI',
 'BJZ.SI',
 'BKA.SI',
 'BKK.SI',
 'BKV.SI',
 'BKW.SI',
 'BKX.SI',
 'BKZ.SI',
 'BLA.SI',
 'BLH.SI',
 'BLR.SI',
 'BLS.SI',
 'BLU.SI',
 'BLW.SI',
 'BMGU.SI',
 'BN2.SI',
 'BN4.SI',
 'BNE.SI',
 'BOU.SI',
 'BPF.SI',
 'BQC.SI',
 'BQD.SI',
 'BQF.SI',
 'BQM.SI',
 'BQN.SI',
 'BQP.SI',
 'BRD.SI',
 'BRS.SI',
 'BS6.SI',
 'BSL.SI',
 'BTE.SI',
 'BTG.SI',
 'BTJ.SI',
 'BTM.SI',
 'BTOU.SI',
 'BTP.SI',
 'BTX.SI',
 'BUOU.SI',
 'BVA.SI',
 'BVP.SI',
 'BVQ.SI',
 'BWCU.SI',
 'BWM.SI',
 'BXE.SI',
 'C04.SI',
 'C05.SI',
 'C06.SI',
 'C07.SI',
 'C09.SI',
 'C13.SI',
 'C29.SI',
 'C2PU.SI',
 'C33.SI',
 'C38U.SI',
 'C41.SI',
 'C52.SI',
 'C6L.SI',
 'C76.SI',
 'C9Q.SI',
 'CC3.SI',
 'CEDU.SI',
 'CHJ.SI',
 'CHZ.SI',
 'CIN.SI',
 'CJLU.SI',
 'CJN.SI',
 'CLN.SI',
 'CMOU.SI',
 'CNE.SI',
 'CRPU.SI',
 'CTO.SI',
 'CWBU.SI',
 'CWCU.SI',
 'CY6U.SI',
 'D01.SI',
 'D03.SI',
 'D05.SI',
 'D5IU.SI',
 'D8DU.SI',
 'DCRU.SI',
 'DHLU.SI',
 'DM0.SI',
 'DU4.SI',
 'E27.SI',
 'E28.SI',
 'E3B.SI',
 'E5H.SI',
 'E6R.SI',
 'E8Z.SI',
 'EB5.SI',
 'EH5.SI',
 'ER0.SI',
 'F03.SI',
 'F13.SI',
 'F17.SI',
 'F1E.SI',
 'F34.SI',
 'F83.SI',
 'F86.SI',
 'F99.SI',
 'F9D.SI',
 'FQ7.SI',
 'G07.SI',
 'G0I.SI',
 'G13.SI',
 'G20.SI',
 'G41.SI',
 'G50.SI',
 'G92.SI',
 'H02.SI',
 'H07.SI',
 'H12.SI',
 'H13.SI',
 'H15.SI',
 'H18.SI',
 'H19.SI',
 'H20.SI',
 'H22.SI',
 'H30.SI',
 'H78.SI',
 'HKB.SI',
 'HMN.SI',
 'I06.SI',
 'I07.SI',
 'I11.SI',
 'I15.SI',
 'I49.SI',
 'IX2.SI',
 'IXOR.SI',
 'J03.SI',
 'J2T.SI',
 'J36.SI',
 'J69U.SI',
 'J85.SI',
 'J91U.SI',
 'JLB.SI',
 'JYEU.SI',
 'K03.SI',
 'K1Q.SI',
 'K29.SI',
 'K2LU.SI',
 'K6S.SI',
 'K71U.SI',
 'K75.SI',
 'KJ5.SI',
 'KUO.SI',
 'L02.SI',
 'L03.SI',
 'L09.SI',
 'L19.SI',
 'L23.SI',
 'L38.SI',
 'LIW.SI',
 'LJ3.SI',
 'LS9.SI',
 'LUY.SI',
 'M01.SI',
 'M04.SI',
 'M05.SI',
 'M11.SI',
 'M12.SI',
 'M14.SI',
 'M1GU.SI',
 'M44U.SI',
 'ME8U.SI',
 'MF6.SI',
 'MR7.SI',
 'MV4.SI',
 'MXNU.SI',
 'MZH.SI',
 'N01.SI',
 'N02.SI',
 'N08.SI',
 'N0Z.SI',
 'N2IU.SI',
 'N33.SI',
 'NC2.SI',
 'NO4.SI',
 'NPW.SI',
 'NR7.SI',
 'NS8U.SI',
 'NTA.SI',
 'NTU.SI',
 'O08.SI',
 'O10.SI',
 'O32.SI',
 'O39.SI',
 'O5RU.SI',
 'O6Z.SI',
 'O9E.SI',
 'ODBU.SI',
 'OU8.SI',
 'OV8.SI',
 'OXMU.SI',
 'OYY.SI',
 'P15.SI',
 'P34.SI',
 'P36.SI',
 'P40U.SI',
 'P52.SI',
 'P74.SI',
 'P7VU.SI',
 'P8A.SI',
 'P8Z.SI',
 'P9D.SI',
 'PA3.SI',
 'PGS.SI',
 'PGU.SI',
 'PJX.SI',
 'Q01.SI',
 'Q0F.SI',
 'Q5T.SI',
 'QC7.SI',
 'QES.SI',
 'QS9.SI',
 'RCQU.SI',
 'RE4.SI',
 'RF1U.SI',
 'RQ1.SI',
 'RS1.SI',
 'RW0U.SI',
 'S07.SI',
 'S08.SI',
 'S19.SI',
 'S20.SI',
 'S23.SI',
 'S29.SI',
 'S2D.SI',
 'S35.SI',
 'S3N.SI',
 'S41.SI',
 'S44.SI',
 'S51.SI',
 'S56.SI',
 'S58.SI',
 'S59.SI',
 'S61.SI',
 'S63.SI',
 'S68.SI',
 'S69.SI',
 'S71.SI',
 'S7OU.SI',
 'S7P.SI',
 'S85.SI',
 'S9B.SI',
 'SK6U.SI',
 'SO7.SI',
 'STG.SI',
 'T12.SI',
 'T13.SI',
 'T14.SI',
 'T24.SI',
 'T39.SI',
 'T41.SI',
 'T43.SI',
 'T55.SI',
 'T6I.SI',
 'T82U.SI',
 'TCU.SI',
 'TQ5.SI',
 'TS0U.SI',
 'U06.SI',
 'U09.SI',
 'U10.SI',
 'U11.SI',
 'U13.SI',
 'U14.SI',
 'U77.SI',
 'U96.SI',
 'U9E.SI',
 'UD1U.SI',
 'UD2.SI',
 'V03.SI',
 'VL6.SI',
 'VT1.SI',
 'VTA.SI',
 'W05.SI',
 'WJP.SI',
 'XJB.SI',
 'XWA.SI',
 'XZL.SI',
 'Y03.SI',
 'Y06.SI',
 'Y35.SI',
 'Y3D.SI',
 'Y45.SI',
 'Y92.SI',
 'Z25.SI',
 'Z59.SI',
 'Z74.SI',
 'Z77.SI']

In [63]:
# create empty dataframe
stock_final = pd.DataFrame()
# iterate over each symbol
for i in Symbols:  
    
    # print the symbol which is being downloaded
    print( str(Symbols.index(i)) + str(' : ') + i, sep=',', end=',', flush=True)  
    
    try:
        # download the stock price 
        stock = []
        stock = yf.download(i,start=start, end=end, interval='1mo', progress=False)
        
        # append the individual stock prices 
        if len(stock) == 0:
            None
        else:
            stock['Name']=i
            stock_final = stock_final.append(stock,sort=False)
    except Exception:
        None

0 : ^STI,1 : 1B0.SI,2 : 1F2.SI,3 : 1F3.SI,4 : 1R6.SI,5 : 49B.SI,6 : 500.SI,7 : 528.SI,8 : 533.SI,9 : 543.SI,10 : 544.SI,11 : 554.SI,12 : 558.SI,13 : 564.SI,14 : 566.SI,15 : 569.SI,16 : 570.SI,17 : 573.SI,18 : 575.SI,19 : 579.SI,20 : 596.SI,21 : 5AB.SI,22 : 5AU.SI,23 : 5CF.SI,24 : 5CP.SI,25 : 5DD.SI,26 : 5DM.SI,27 : 5DO.SI,28 : 5DP.SI,29 : 5GD.SI,30 : 5GI.SI,31 : 5GJ.SI,32 : 5IC.SI,33 : 5IG.SI,34 : 5JK.SI,35 : 5JS.SI,36 : 5KI.SI,37 : 5LY.SI,38 : 5MZ.SI,39 : 5NF.SI,40 : 5NV.SI,41 : 5PC.SI,42 : 5SO.SI,43 : 5SR.SI,44 : 5TT.SI,45 : 5UX.SI,46 : 5VJ.SI,47 : 5VS.SI,48 : 8A1.SI,49 : 8AZ.SI,50 : 8U7U.SI,
1 Failed download:
- 8U7U.SI: No data found, symbol may be delisted
51 : 9CI.SI,52 : A04.SI,53 : A17U.SI,54 : A26.SI,55 : A30.SI,56 : A31.SI,57 : A33.SI,58 : A34.SI,59 : A50.SI,60 : A55.SI,61 : A7RU.SI,62 : ACV.SI,63 : ADN.SI,64 : AGS.SI,65 : AIY.SI,66 : AJ2.SI,67 : AJBU.SI,68 : AP4.SI,69 : AU8U.SI,70 : AUE.SI,71 : AVM.SI,72 : AVX.SI,73 : AW9U.SI,74 : AWC.SI,75 : AWE.SI,76 : AWG.SI,77 : AWI.SI,78 : AWK.SI,79 : AWM.SI,80 : AWS.SI,81 : AWV.SI,82 : AWX.SI,83 : AWZ.SI,84 : AXB.SI,85 : AYN.SI,86 : AYV.SI,87 : AZA.SI,88 : AZT.SI,89 : B26.SI,90 : B28.SI,91 : B49.SI,92 : B58.SI,93 : B61.SI,94 : B69.SI,95 : B73.SI,96 : B9S.SI,97 : BAZ.SI,98 : BBP.SI,99 : BBW.SI,100 : BCD.SI,101 : BCV.SI,102 : BCY.SI,103 : BCZ.SI,104 : BDA.SI,105 : BDF.SI,106 : BDR.SI,107 : BDU.SI,108 : BDX.SI,109 : BEC.SI,110 : BEH.SI,111 : BEI.SI,112 : BEW.SI,113 : BEZ.SI,114 : BFI.SI,115 : BFK.SI,116 : BFT.SI,117 : BFU.SI,118 : BHD.SI,119 : BHK.SI,120 : BHU.SI,121 : BIP.SI,122 : BIX.SI,123 : BJD.SI,124 : BJW.SI,125 : BJZ.SI,126 : BKA.SI,127 : BKK.SI,128 : BKV.SI,129 : BKW.SI,130 : BKX.SI,131 : BKZ.SI,132 : BLA.SI,133 : BLH.SI,134 : BLR.SI,135 : BLS.SI,136 : BLU.SI,137 : BLW.SI,138 : BMGU.SI,139 : BN2.SI,140 : BN4.SI,141 : BNE.SI,142 : BOU.SI,143 : BPF.SI,144 : BQC.SI,145 : BQD.SI,146 : BQF.SI,147 : BQM.SI,148 : BQN.SI,149 : BQP.SI,150 : BRD.SI,151 : BRS.SI,152 : BS6.SI,153 : BSL.SI,154 : BTE.SI,155 : BTG.SI,156 : BTJ.SI,157 : BTM.SI,158 : BTOU.SI,159 : BTP.SI,160 : BTX.SI,161 : BUOU.SI,162 : BVA.SI,163 : BVP.SI,164 : BVQ.SI,165 : BWCU.SI,166 : BWM.SI,167 : BXE.SI,168 : C04.SI,169 : C05.SI,170 : C06.SI,171 : C07.SI,172 : C09.SI,173 : C13.SI,174 : C29.SI,175 : C2PU.SI,176 : C33.SI,177 : C38U.SI,178 : C41.SI,179 : C52.SI,180 : C6L.SI,181 : C76.SI,182 : C9Q.SI,183 : CC3.SI,184 : CEDU.SI,185 : CHJ.SI,186 : CHZ.SI,187 : CIN.SI,188 : CJLU.SI,189 : CJN.SI,190 : CLN.SI,191 : CMOU.SI,192 : CNE.SI,193 : CRPU.SI,194 : CTO.SI,195 : CWBU.SI,196 : CWCU.SI,
1 Failed download:
- CWCU.SI: No data found for this date range, symbol may be delisted
197 : CY6U.SI,198 : D01.SI,199 : D03.SI,200 : D05.SI,201 : D5IU.SI,202 : D8DU.SI,203 : DCRU.SI,204 : DHLU.SI,205 : DM0.SI,206 : DU4.SI,207 : E27.SI,208 : E28.SI,209 : E3B.SI,210 : E5H.SI,211 : E6R.SI,212 : E8Z.SI,213 : EB5.SI,214 : EH5.SI,215 : ER0.SI,216 : F03.SI,217 : F13.SI,218 : F17.SI,219 : F1E.SI,220 : F34.SI,221 : F83.SI,222 : F86.SI,223 : F99.SI,224 : F9D.SI,225 : FQ7.SI,226 : G07.SI,227 : G0I.SI,228 : G13.SI,229 : G20.SI,230 : G41.SI,231 : G50.SI,232 : G92.SI,233 : H02.SI,234 : H07.SI,235 : H12.SI,236 : H13.SI,237 : H15.SI,238 : H18.SI,239 : H19.SI,240 : H20.SI,241 : H22.SI,242 : H30.SI,243 : H78.SI,244 : HKB.SI,245 : HMN.SI,246 : I06.SI,247 : I07.SI,248 : I11.SI,249 : I15.SI,250 : I49.SI,251 : IX2.SI,252 : IXOR.SI,
1 Failed download:
- IXOR.SI: No data found, symbol may be delisted
253 : J03.SI,254 : J2T.SI,255 : J36.SI,256 : J69U.SI,257 : J85.SI,258 : J91U.SI,259 : JLB.SI,260 : JYEU.SI,261 : K03.SI,262 : K1Q.SI,263 : K29.SI,264 : K2LU.SI,265 : K6S.SI,266 : K71U.SI,267 : K75.SI,268 : KJ5.SI,269 : KUO.SI,270 : L02.SI,271 : L03.SI,272 : L09.SI,273 : L19.SI,274 : L23.SI,275 : L38.SI,276 : LIW.SI,277 : LJ3.SI,278 : LS9.SI,279 : LUY.SI,280 : M01.SI,281 : M04.SI,282 : M05.SI,283 : M11.SI,284 : M12.SI,
1 Failed download:
- M12.SI: No data found for this date range, symbol may be delisted
285 : M14.SI,286 : M1GU.SI,287 : M44U.SI,288 : ME8U.SI,289 : MF6.SI,290 : MR7.SI,291 : MV4.SI,292 : MXNU.SI,293 : MZH.SI,294 : N01.SI,295 : N02.SI,296 : N08.SI,297 : N0Z.SI,298 : N2IU.SI,299 : N33.SI,300 : NC2.SI,301 : NO4.SI,302 : NPW.SI,303 : NR7.SI,304 : NS8U.SI,305 : NTA.SI,
1 Failed download:
- NTA.SI: No data found, symbol may be delisted
306 : NTU.SI,307 : O08.SI,308 : O10.SI,309 : O32.SI,310 : O39.SI,311 : O5RU.SI,312 : O6Z.SI,
1 Failed download:
- O6Z.SI: No data found, symbol may be delisted
313 : O9E.SI,314 : ODBU.SI,315 : OU8.SI,316 : OV8.SI,317 : OXMU.SI,318 : OYY.SI,319 : P15.SI,320 : P34.SI,321 : P36.SI,322 : P40U.SI,323 : P52.SI,324 : P74.SI,325 : P7VU.SI,326 : P8A.SI,327 : P8Z.SI,328 : P9D.SI,329 : PA3.SI,330 : PGS.SI,
1 Failed download:
- PGS.SI: No data found, symbol may be delisted
331 : PGU.SI,332 : PJX.SI,
1 Failed download:
- PJX.SI: No data found, symbol may be delisted
333 : Q01.SI,334 : Q0F.SI,335 : Q5T.SI,336 : QC7.SI,337 : QES.SI,338 : QS9.SI,339 : RCQU.SI,
1 Failed download:
- RCQU.SI: No data found, symbol may be delisted
340 : RE4.SI,341 : RF1U.SI,
1 Failed download:
- RF1U.SI: No data found, symbol may be delisted
342 : RQ1.SI,343 : RS1.SI,344 : RW0U.SI,345 : S07.SI,346 : S08.SI,347 : S19.SI,348 : S20.SI,349 : S23.SI,350 : S29.SI,351 : S2D.SI,
1 Failed download:
- S2D.SI: No data found, symbol may be delisted
352 : S35.SI,353 : S3N.SI,354 : S41.SI,355 : S44.SI,356 : S51.SI,357 : S56.SI,358 : S58.SI,359 : S59.SI,360 : S61.SI,361 : S63.SI,362 : S68.SI,363 : S69.SI,364 : S71.SI,365 : S7OU.SI,366 : S7P.SI,367 : S85.SI,368 : S9B.SI,369 : SK6U.SI,370 : SO7.SI,
1 Failed download:
- SO7.SI: No data found, symbol may be delisted
371 : STG.SI,372 : T12.SI,373 : T13.SI,374 : T14.SI,375 : T24.SI,376 : T39.SI,377 : T41.SI,378 : T43.SI,379 : T55.SI,380 : T6I.SI,381 : T82U.SI,382 : TCU.SI,383 : TQ5.SI,384 : TS0U.SI,385 : U06.SI,386 : U09.SI,387 : U10.SI,388 : U11.SI,389 : U13.SI,390 : U14.SI,391 : U77.SI,392 : U96.SI,393 : U9E.SI,394 : UD1U.SI,395 : UD2.SI,396 : V03.SI,397 : VL6.SI,398 : VT1.SI,
1 Failed download:
- VT1.SI: No data found, symbol may be delisted
399 : VTA.SI,400 : W05.SI,401 : WJP.SI,402 : XJB.SI,403 : XWA.SI,
1 Failed download:
- XWA.SI: No data found for this date range, symbol may be delisted
404 : XZL.SI,405 : Y03.SI,406 : Y06.SI,407 : Y35.SI,408 : Y3D.SI,409 : Y45.SI,410 : Y92.SI,411 : Z25.SI,412 : Z59.SI,413 : Z74.SI,414 : Z77.SI,

In [64]:
df = stock_final
df.reset_index(inplace=True)
df = df.filter(['Name', 'Date', 'Close'])
df.head()

   Name       Date        Close
0  ^STI 2014-01-01  3027.219971
1  ^STI 2014-02-01  3110.780029
2  ^STI 2014-03-01  3188.620117
3  ^STI 2014-04-01  3264.709961
4  ^STI 2014-05-01  3295.850098

In [70]:
# Filter just jan 1
# df['Date'] = pd.to_datetime(df['Date']) -- if column is not datetime yet
new_df = df[df['Date'].dt.month == 1]
new_df

         Name       Date        Close
0        ^STI 2014-01-01  3027.219971
12       ^STI 2015-01-01  3391.199951
24       ^STI 2016-01-01  2629.110107
36       ^STI 2017-01-01  3046.800049
48       ^STI 2018-01-01  3533.989990
...       ...        ...          ...
40808  Z77.SI 2018-01-01     3.550000
40820  Z77.SI 2019-01-01     3.000000
40832  Z77.SI 2020-01-01     3.300000
40844  Z77.SI 2021-01-01     2.370000
40856  Z77.SI 2022-01-01     2.460000

[3549 rows x 3 columns]

In [71]:
new_df['Year'] = new_df['Date'].map(lambda x : x.year)
new_df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

         Name       Date        Close  Year
0        ^STI 2014-01-01  3027.219971  2014
12       ^STI 2015-01-01  3391.199951  2015
24       ^STI 2016-01-01  2629.110107  2016
36       ^STI 2017-01-01  3046.800049  2017
48       ^STI 2018-01-01  3533.989990  2018
...       ...        ...          ...   ...
40808  Z77.SI 2018-01-01     3.550000  2018
40820  Z77.SI 2019-01-01     3.000000  2019
40832  Z77.SI 2020-01-01     3.300000  2020
40844  Z77.SI 2021-01-01     2.370000  2021
40856  Z77.SI 2022-01-01     2.460000  2022

[3549 rows x 4 columns]

In [72]:
# DONE?
final_df = new_df.filter(['Name', 'Year', 'Close'])
final_df

         Name  Year        Close
0        ^STI  2014  3027.219971
12       ^STI  2015  3391.199951
24       ^STI  2016  2629.110107
36       ^STI  2017  3046.800049
48       ^STI  2018  3533.989990
...       ...   ...          ...
40808  Z77.SI  2018     3.550000
40820  Z77.SI  2019     3.000000
40832  Z77.SI  2020     3.300000
40844  Z77.SI  2021     2.370000
40856  Z77.SI  2022     2.460000

[3549 rows x 3 columns]

In [74]:
df2 = final_df.groupby(['Name','Year']).sum()
df3 = df2.unstack(level=-1).add_prefix('p_')

output_df = df3['p_Close'].reset_index()

output_df

Year,Name,p_2014,p_2015,p_2016,p_2017,p_2018,p_2019,p_2020,p_2021,p_2022
0,1B0.SI,NaN,0.050000,0.177500,0.520000,0.510000,0.325000,0.21500,0.101250,0.052000
1,1F2.SI,NaN,NaN,NaN,NaN,0.280000,0.255000,0.24000,0.530000,0.730000
2,1F3.SI,NaN,NaN,NaN,NaN,0.220000,0.156000,0.07200,0.240000,0.070000
3,1R6.SI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.345000
4,49B.SI,11.105685,10.531253,6.127274,2.374319,1.914773,0.670170,0.67017,0.363806,0.147000
...,...,...,...,...,...,...,...,...,...,...
394,Z25.SI,1.120000,1.010000,1.020000,1.390000,1.850000,1.270000,1.15000,1.100000,1.150000
395,Z59.SI,0.650240,0.540000,0.445000,0.575000,0.505000,0.340000,0.31500,0.275000,0.134000
396,Z74.SI,3.530000,4.080000,3.510000,3.870000,3.540000,3.020000,3.30000,2.360000,2.430000
397,Z77.SI,3.500000,4.070000,3.510000,3.850000,3.550000,3.000000,3.30000,2.370000,2.460000
398,^STI,3027.219971,3391.199951,2629.110107,3046.800049,3533.989990,3190.169922,3153.72998,2902.520020,3249.590088

In [75]:
output_df.to_csv("Data_B.csv")